#!/bin/bash
# Quick setup script for deployment

echo "✅ Deployment files added:"
echo ""
echo "📄 Files created:"
echo "   - Dockerfile          (Container definition)"
echo "   - fly.toml            (Fly.io configuration)"
echo "   - .dockerignore       (Build exclusions)"
echo "   - DEPLOYMENT.md       (Detailed guide)"
echo "   - deploy.sh           (Quick deploy script)"
echo ""

echo "🚀 Next steps:"
echo ""
echo "1. Make sure you have flyctl installed:"
echo "   https://fly.io/docs/getting-started/installing-flyctl"
echo ""
echo "2. Login to Fly.io:"
echo "   flyctl auth login"
echo ""
echo "3. Deploy your app:"
echo "   ./deploy.sh"
echo ""
echo "   OR manually:"
echo "   flyctl deploy"
echo ""
echo "4. Monitor your deployment:"
echo "   flyctl logs"
echo ""
echo "📚 For more details, see DEPLOYMENT.md"
